<?php

namespace Edahira\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Edahira\UserBundle\Entity\Utilisateurs;

/**
 * UtilisateursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateursRepository extends EntityRepository
{
    public function nullActiveDahira(){

        $qb = $this->createQueryBuilder('u')->update()
                   ->set('u.activeDahira', 'null')
                   ->getQuery();

        return $qb->getResult();
    }

    public function getUsersDahira($dahira){
        $qb =  $this->createQueryBuilder('u')
                    ->select('u.id')
                    ->leftJoin('u.dahiras', 'd')
                    ->where("d.id = :dahira")
                    ->setParameter('dahira', $dahira)
                    ->getQuery();
        $result = array();
        foreach ($qb->getResult() as $id) {
            $result[] = $id['id'];
        }
        return $result;
    }

    public function getOtherUsers($dahira){
    	// echo $dahira;exit;
        $qb =  $this->createQueryBuilder('u');
        $qb->where($qb->expr()->notIn('u.id', $this->getUsersDahira($dahira)));
        // $query = $qb->getQuery();

        return $qb;
    }
}