Edahira\DahiraBundle\Entity\Caisses:
    type: entity
    table: null
    repositoryClass: Edahira\DahiraBundle\Entity\CaissesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: '100'
        description:
            type: string
            length: '255'
            nullable: true
        fond:
            type: integer
            nullable: true
        etat:
            type: boolean
    oneToMany:
        typeevenement:
            targetEntity: Typeevenement
            mappedBy: caisse
        charges:
            targetEntity: Charges
            mappedBy: caisse
        depenses:
            targetEntity: Depenses
            mappedBy: caisse
    manyToOne:
        dahira:
            targetEntity: Dahira
            inversedBy: caisses
            joinColumn:
                nullable: false
    lifecycleCallbacks: {  }