Edahira\DahiraBundle\Entity\Cotisations:
    type: entity
    table: null
    repositoryClass: Edahira\DahiraBundle\Entity\CotisationsRepository
    id:
        evenement:
            associationKey: true
        membre:
            associationKey: true
    fields:
        date:
            type: date
        montant:
            type: integer
        etat:
            type: boolean
    manyToOne:
        evenement:
            targetEntity: Evenement
            inversedBy: cotisations
        membre:
            targetEntity: Membres
            inversedBy: cotisations
    lifecycleCallbacks: {  }