Edahira\DahiraBundle\Entity\Evenement:
    type: entity
    table: null
    repositoryClass: Edahira\DahiraBundle\Entity\EvenementRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: date
    oneToMany:
        cotisations:
            targetEntity: Cotisations
            mappedBy: evenement
        dons:
            targetEntity: Dons
            mappedBy: evenement
    manyToOne:
        typeevenement:
            targetEntity: Typeevenement
            inversedBy: evenement
        membre:
            targetEntity: Membres
            inversedBy: dahiras
        dahira:
            targetEntity: Dahira
            inversedBy: evenement
            joinColumn:
                nullable: false
    lifecycleCallbacks: {  }
