Edahira\DahiraBundle\Entity\Membres:
    type: entity
    table: null
    repositoryClass: Edahira\DahiraBundle\Entity\MembresRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        prenom:
            type: string
            length: '100'
        nom:
            type: string
            length: '100'
        adresse:
            type: string
            length: '255'
            nullable: true
        email:
            type: string
            length: '50'
            nullable: true
        telephone1:
            type: string
            length: '20'
            nullable: true
        telephone2:
            type: string
            length: '20'
            nullable: true
        etat:
            type: boolean
            nullable: true
    manyToOne:
        categorie:
            targetEntity: Categories
            inversedBy: membres
            joinColumn:
                nullable: false
        dahira:
            targetEntity: Dahira
            inversedBy: membres
            joinColumn:
                nullable: false
    oneToMany:
        versements:
            targetEntity: Versements
            mappedBy: membre
            cascade: [persist, remove]
        cotisations:
            targetEntity: Cotisations
            mappedBy: membre
            cascade: [persist, remove]
        dahiras:
            targetEntity: Evenement
            mappedBy: membre
    lifecycleCallbacks: {  }