Edahira\DahiraBundle\Entity\Typeevenement:
    type: entity
    table: null
    repositoryClass: Edahira\DahiraBundle\Entity\TypeevenementRepository
    id:
        id:
            type: integer
            id: true
    fields:
        nom:
            type: string
            length: '100'
        periode:
            type: integer
        jourdesemaine:
            type: string
            length: '100'
            nullable: true
    oneToMany:
        evenement:
            targetEntity: Evenement
            mappedBy: typeevenement
        cotisations:
            targetEntity: MontantCotisations
            mappedBy: typeevenement
            cascade: [persist]
    manyToOne:
        caisse:
            targetEntity: Caisses
            inversedBy: typeevenement
        dahira:
            targetEntity: Dahira
            inversedBy: typeevenement
            joinColumn:
                nullable: false
    lifecycleCallbacks: {  }
