<?php

namespace Proxies\__CG__\Edahira\DahiraBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evenement extends \Edahira\DahiraBundle\Entity\Evenement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'date', 'membre', 'cotisations', 'typeevenement', 'dons', 'dahira');
        }

        return array('__isInitialized__', 'id', 'date', 'membre', 'cotisations', 'typeevenement', 'dons', 'dahira');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evenement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function addMembre(\Edahira\DahiraBundle\Entity\Membres $membre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMembre', array($membre));

        return parent::addMembre($membre);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMembre(\Edahira\DahiraBundle\Entity\Membres $membre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMembre', array($membre));

        return parent::removeMembre($membre);
    }

    /**
     * {@inheritDoc}
     */
    public function getMembre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMembre', array());

        return parent::getMembre();
    }

    /**
     * {@inheritDoc}
     */
    public function addCotisation(\Edahira\DahiraBundle\Entity\Cotisations $cotisations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCotisation', array($cotisations));

        return parent::addCotisation($cotisations);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCotisation(\Edahira\DahiraBundle\Entity\Cotisations $cotisations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCotisation', array($cotisations));

        return parent::removeCotisation($cotisations);
    }

    /**
     * {@inheritDoc}
     */
    public function getCotisations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCotisations', array());

        return parent::getCotisations();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeevenement(\Edahira\DahiraBundle\Entity\Typeevenement $typeevenement = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeevenement', array($typeevenement));

        return parent::setTypeevenement($typeevenement);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeevenement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeevenement', array());

        return parent::getTypeevenement();
    }

    /**
     * {@inheritDoc}
     */
    public function setMembre(\Edahira\DahiraBundle\Entity\Membres $membre = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMembre', array($membre));

        return parent::setMembre($membre);
    }

    /**
     * {@inheritDoc}
     */
    public function setDahira(\Edahira\DahiraBundle\Entity\Dahira $dahira = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDahira', array($dahira));

        return parent::setDahira($dahira);
    }

    /**
     * {@inheritDoc}
     */
    public function getDahira()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDahira', array());

        return parent::getDahira();
    }

    /**
     * {@inheritDoc}
     */
    public function addDon(\Edahira\DahiraBundle\Entity\Dons $dons)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDon', array($dons));

        return parent::addDon($dons);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDon(\Edahira\DahiraBundle\Entity\Dons $dons)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDon', array($dons));

        return parent::removeDon($dons);
    }

    /**
     * {@inheritDoc}
     */
    public function getDons()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDons', array());

        return parent::getDons();
    }

}
