<?php

namespace Proxies\__CG__\Edahira\DahiraBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Membres extends \Edahira\DahiraBundle\Entity\Membres implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'prenom', 'nom', 'sexe', 'adresse', 'email', 'telephone1', 'telephone2', 'dahiras', 'cotisations', 'etat', 'categorie', 'versements', 'dahira');
        }

        return array('__isInitialized__', 'id', 'prenom', 'nom', 'sexe', 'adresse', 'email', 'telephone1', 'telephone2', 'dahiras', 'cotisations', 'etat', 'categorie', 'versements', 'dahira');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Membres $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function getAffichage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAffichage', array());

        return parent::getAffichage();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone1($telephone1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone1', array($telephone1));

        return parent::setTelephone1($telephone1);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone1', array());

        return parent::getTelephone1();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone2($telephone2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone2', array($telephone2));

        return parent::setTelephone2($telephone2);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone2', array());

        return parent::getTelephone2();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', array($etat));

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', array());

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function addCotisation(\Edahira\DahiraBundle\Entity\Cotisations $cotisations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCotisation', array($cotisations));

        return parent::addCotisation($cotisations);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCotisation(\Edahira\DahiraBundle\Entity\Cotisations $cotisations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCotisation', array($cotisations));

        return parent::removeCotisation($cotisations);
    }

    /**
     * {@inheritDoc}
     */
    public function getCotisations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCotisations', array());

        return parent::getCotisations();
    }

    /**
     * {@inheritDoc}
     */
    public function addDahira(\Edahira\DahiraBundle\Entity\Dahira $dahiras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDahira', array($dahiras));

        return parent::addDahira($dahiras);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDahira(\Edahira\DahiraBundle\Entity\Dahira $dahiras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDahira', array($dahiras));

        return parent::removeDahira($dahiras);
    }

    /**
     * {@inheritDoc}
     */
    public function getDahiras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDahiras', array());

        return parent::getDahiras();
    }

    /**
     * {@inheritDoc}
     */
    public function setDahiras(\Edahira\DahiraBundle\Entity\Evenement $dahiras = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDahiras', array($dahiras));

        return parent::setDahiras($dahiras);
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe($sexe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', array($sexe));

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', array());

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(\Edahira\DahiraBundle\Entity\Categories $categorie = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', array($categorie));

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', array());

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function addVersement(\Edahira\DahiraBundle\Entity\Versements $versements)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVersement', array($versements));

        return parent::addVersement($versements);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVersement(\Edahira\DahiraBundle\Entity\Versements $versements)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVersement', array($versements));

        return parent::removeVersement($versements);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersements()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersements', array());

        return parent::getVersements();
    }

    /**
     * {@inheritDoc}
     */
    public function setDahira(\Edahira\DahiraBundle\Entity\Dahira $dahira = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDahira', array($dahira));

        return parent::setDahira($dahira);
    }

    /**
     * {@inheritDoc}
     */
    public function getDahira()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDahira', array());

        return parent::getDahira();
    }

}
