<?php

namespace Proxies\__CG__\Edahira\DahiraBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Charges extends \Edahira\DahiraBundle\Entity\Charges implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'objet', 'echeance', 'montants', 'etat', 'versements', 'caisse', 'dons', 'dahira');
        }

        return array('__isInitialized__', 'id', 'objet', 'echeance', 'montants', 'etat', 'versements', 'caisse', 'dons', 'dahira');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Charges $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjet($objet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjet', array($objet));

        return parent::setObjet($objet);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjet', array());

        return parent::getObjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setEcheance($echeance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEcheance', array($echeance));

        return parent::setEcheance($echeance);
    }

    /**
     * {@inheritDoc}
     */
    public function getEcheance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEcheance', array());

        return parent::getEcheance();
    }

    /**
     * {@inheritDoc}
     */
    public function addMontant(\Edahira\DahiraBundle\Entity\MontantCharges $montants)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMontant', array($montants));

        return parent::addMontant($montants);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMontant(\Edahira\DahiraBundle\Entity\MontantCharges $montants)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMontant', array($montants));

        return parent::removeMontant($montants);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontants()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontants', array());

        return parent::getMontants();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaisse(\Edahira\DahiraBundle\Entity\Caisses $caisse = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaisse', array($caisse));

        return parent::setCaisse($caisse);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaisse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaisse', array());

        return parent::getCaisse();
    }

    /**
     * {@inheritDoc}
     */
    public function addVersement(\Edahira\DahiraBundle\Entity\Versements $versements)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVersement', array($versements));

        return parent::addVersement($versements);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVersement(\Edahira\DahiraBundle\Entity\Versements $versements)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVersement', array($versements));

        return parent::removeVersement($versements);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersements()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersements', array());

        return parent::getVersements();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', array($etat));

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', array());

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDahira(\Edahira\DahiraBundle\Entity\Dahira $dahira = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDahira', array($dahira));

        return parent::setDahira($dahira);
    }

    /**
     * {@inheritDoc}
     */
    public function getDahira()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDahira', array());

        return parent::getDahira();
    }

    /**
     * {@inheritDoc}
     */
    public function addDon(\Edahira\DahiraBundle\Entity\Dons $dons)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDon', array($dons));

        return parent::addDon($dons);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDon(\Edahira\DahiraBundle\Entity\Dons $dons)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDon', array($dons));

        return parent::removeDon($dons);
    }

    /**
     * {@inheritDoc}
     */
    public function getDons()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDons', array());

        return parent::getDons();
    }

}
