<?php

namespace Proxies\__CG__\Edahira\DahiraBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Typeevenement extends \Edahira\DahiraBundle\Entity\Typeevenement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'nom', 'evenement', 'periode', 'jourdesemaine', 'caisse', 'cotisations', 'dahira');
        }

        return array('__isInitialized__', 'id', 'nom', 'evenement', 'periode', 'jourdesemaine', 'caisse', 'cotisations', 'dahira');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Typeevenement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function addEvenement(\Edahira\DahiraBundle\Entity\Evenement $evenement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEvenement', array($evenement));

        return parent::addEvenement($evenement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEvenement(\Edahira\DahiraBundle\Entity\Evenement $evenement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEvenement', array($evenement));

        return parent::removeEvenement($evenement);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvenement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvenement', array());

        return parent::getEvenement();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriode($periode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriode', array($periode));

        return parent::setPeriode($periode);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriode', array());

        return parent::getPeriode();
    }

    /**
     * {@inheritDoc}
     */
    public function setJourdesemaine($jourdesemaine)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJourdesemaine', array($jourdesemaine));

        return parent::setJourdesemaine($jourdesemaine);
    }

    /**
     * {@inheritDoc}
     */
    public function getJourdesemaine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJourdesemaine', array());

        return parent::getJourdesemaine();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaisse(\Edahira\DahiraBundle\Entity\Caisses $caisse = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaisse', array($caisse));

        return parent::setCaisse($caisse);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaisse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaisse', array());

        return parent::getCaisse();
    }

    /**
     * {@inheritDoc}
     */
    public function addCotisation(\Edahira\DahiraBundle\Entity\MontantCotisations $cotisations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCotisation', array($cotisations));

        return parent::addCotisation($cotisations);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCotisation(\Edahira\DahiraBundle\Entity\MontantCotisations $cotisations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCotisation', array($cotisations));

        return parent::removeCotisation($cotisations);
    }

    /**
     * {@inheritDoc}
     */
    public function getCotisations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCotisations', array());

        return parent::getCotisations();
    }

    /**
     * {@inheritDoc}
     */
    public function setDahira(\Edahira\DahiraBundle\Entity\Dahira $dahira = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDahira', array($dahira));

        return parent::setDahira($dahira);
    }

    /**
     * {@inheritDoc}
     */
    public function getDahira()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDahira', array());

        return parent::getDahira();
    }

}
