<?php

namespace Edahira\DahiraBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CaissesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaissesRepository extends EntityRepository
{
	public function getCaisses($dahira){
		$qb = $this->createQueryBuilder('c')
                ->leftJoin('c.dahira', 'd')
                ->addSelect('d')
                ->where("d.id = :dahira")
                ->setParameter('dahira', $dahira);
                // ->getQuery();

	    return $qb;//->getResult();//
	}

	public function getActivesCaisses($dahira){
		
		$qb = $this->createQueryBuilder('c')
                   ->leftJoin('c.dahira', 'd')
                   ->addSelect('d')
                   ->where("d.id = :dahira")
                   ->setParameter('dahira', $dahira)
				   ->andWhere('c.etat = '.true);
				   // ->getQuery();
		return $qb;//->getResult();
	}
	
				   
	public function getCaisse($îd){
		
		$qb = $this->createQueryBuilder('c')
				   ->where('c.id = '.$id)
				   ->getQuery();
				   
		return $qb->getResult();
	}
}
