<?php

namespace Edahira\DahiraBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CaissesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaissesRepository extends EntityRepository
{
	public function getCaisses($nombreParPage, $page){
		
		$qb = $this->createQueryBuilder('c')
		           ->leftJoin('c.typeCaisse','t')
				   ->addSelect('t')
				   ->getQuery();
		$qb->setFirstResult(($page-1) * $nombreParPage)
           ->setMaxResults($nombreParPage);
           
		return new Paginator($qb);
	}

	public function getActivesCaisses($nombreParPage, $page){
		
		$qb = $this->createQueryBuilder('c')
		           ->leftJoin('c.typeCaisse','t')
				   ->addSelect('t')
				   ->where('c.etat = '.true)
				   ->getQuery();
		$qb->setFirstResult(($page-1) * $nombreParPage)
           ->setMaxResults($nombreParPage);
           
		return new Paginator($qb);
	}
	
				   
	public function getCaisse($îd){
		
		$qb = $this->createQueryBuilder('c')
		           ->leftJoin('c.typeCaisse','t')
				   ->addSelect('t')
				   ->where('c.id = '.$id)
				   ->getQuery();
				   
		return $qb->getResult();
	}
}
