<?php

namespace Edahira\DahiraBundle\Entity;

use Doctrine\ORM\EntityRepository;
// use Edahira\DahiraBundle\Entity\Dahira;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesRepository extends EntityRepository
{
	public function getCategories($dahira){
		$qb = $this->createQueryBuilder('c')
                ->leftJoin('c.dahira', 'd')
                ->addSelect('d')
                ->where("d.id = :dahira")
                ->setParameter('dahira', $dahira);
                // ->getQuery();

	    return $qb;//->getResult();//
	}

}
