<?php

namespace Edahira\DahiraBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * ChargesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChargesRepository extends EntityRepository
{
	public function getCharges($dahira){
		$qb = $this->createQueryBuilder('c')
                ->leftJoin('c.dahira', 'd')
                ->addSelect('d')
                ->where("d.id = :dahira")
                ->andWhere("c.etat = :etat")
                ->setParameter('etat', 1)
                ->setParameter('dahira', $dahira);
                // ->getQuery();

	    return $qb;//->getResult();//
	}

	public function getActivesCharges($dahira){
		$qb =  $this->createQueryBuilder('c')
                ->leftJoin('c.dahira', 'd')
                ->addSelect('d')
                ->where("d.id = :dahira")
                ->andWhere("c.etat = :etat")
                ->setParameter('etat', 1)
                ->setParameter('dahira', $dahira)
				->getQuery();
				   
		return $qb->getResult();
	}

	public function findLast(){
		$qb = $this->createQueryBuilder('c')
		           ->orderBy('c.id', 'DESC')
                   ->setMaxResults(1)
                   ->getQuery()
                   ->getSingleResult();
        return $qb;
	}
}