<?php

namespace Edahira\DahiraBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * DepensesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepensesRepository extends EntityRepository
{
	public function getDepenses($nombreParPage, $page){

		$qb = $this->createQueryBuilder('d')
				   ->getQuery();
				   
		$qb->setFirstResult(($page-1) * $nombreParPage)
           ->setMaxResults($nombreParPage);
           
		return new Paginator($qb);
	}
}