<?php

namespace Edahira\DahiraBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends EntityRepository
{
	public function getEvenements($nombreParPage, $page){
		
		$qb = $this->createQueryBuilder('e')
		           ->leftJoin('e.typeevenement','t')
				   ->addSelect('t')
		           ->leftJoin('e.membre','m')
				   ->addSelect('m')
				   ->getQuery();
		$qb->setFirstResult(($page-1) * $nombreParPage)
           ->setMaxResults($nombreParPage);
           
		return new Paginator($qb);
	}	
				   
	public function getEvenement($id){
		
		$qb = $this->createQueryBuilder('e')
		           ->leftJoin('e.typeevenement','t')
				   ->addSelect('t')
		           ->leftJoin('e.membre','m')
				   ->addSelect('m')
				   ->where('e.id = '.$id)
				   ->getQuery();
        return $qb->getResult();
	}

	public function getEvenementType($id){
		
		$qb = $this->createQueryBuilder('e')
		           ->leftJoin('e.typeevenement','t')
				   ->addSelect('t')
				   ->where('t.id = '.$id)
				   ->getQuery();
        return $qb->getResult();
	}
}
