<?php

namespace Edahira\DahiraBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends EntityRepository
{
	public function getEvenements($dahira){
		$qb = $this->createQueryBuilder('e')
                ->leftJoin('e.dahira', 'd')
                ->addSelect('d')
                ->where("d.id = :dahira")
                ->setParameter('dahira', $dahira);
                // ->getQuery();

	    return $qb;//->getResult();//
	}
	
	public function getEvenementType($id){
		
		$qb = $this->createQueryBuilder('e')
		           ->leftJoin('e.typeevenement','t')
				   ->addSelect('t')
				   ->where('t.id = :id')
				   ->setParameter('id', $id)
				   ->getQuery();

        return $qb->getResult();
	}
}