<?php

namespace Edahira\DahiraBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * MembresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembresRepository extends EntityRepository
{
	public function getMembres($dahira){
		$qb = $this->createQueryBuilder('m')
                ->leftJoin('m.dahira', 'd')
                ->addSelect('d')
                ->where("d.id = :dahira")
                ->andWhere("m.etat = :etat")
				->orderBy('m.prenom', 'ASC')
                ->setParameter('etat', 1)
                ->setParameter('dahira', $dahira);
                // ->getQuery();

	    return $qb;//->getResult();//
	}

	public function getCotisationsMembreEventType($membre, $type){
		$qb = $this->createQueryBuilder('m')
		           ->rightJoin('m.cotisations','c')
				   ->addSelect('c')
		           ->rightJoin('c.evenement','e')
				   ->addSelect('c')
		           ->rightJoin('c.typeevenement','t')
				   ->addSelect('t')
				   ->where('t.id = ?', $type)
				   ->andWhere('m.id = ?', $membre)
				   ->getQuery();
				   
		return $qb->getResult();
	}
}