<?php

namespace Edahira\DahiraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MontantChargesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MontantChargesRepository extends EntityRepository
{
}
