<?php

namespace Edahira\DahiraBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TypecaissesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypecaissesRepository extends EntityRepository
{
	public function getTypecaisses($nombreParPage, $page){
		$qb = $this->createQueryBuilder('t')
				   ->getQuery();
				   
		$qb->setFirstResult(($page-1) * $nombreParPage)
           ->setMaxResults($nombreParPage);
           
		return new Paginator($qb);
	}
}