<?php

namespace Edahira\DahiraBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TypeevenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeevenementRepository extends EntityRepository
{
    public function getTypeevenemets($nombreParPage, $page){
    	$qb = $this->createQueryBuilder('t')
    			   ->getQuery();

    	$qb->setFirstResult(($page-1) * $nombreParPage)
             ->setMaxResults($nombreParPage);
             
    	return new Paginator($qb);
    }

    public function getTypes($dahira){
    	$qb = $this->createQueryBuilder('t')
                  ->leftJoin('t.dahira', 'd')
                  ->addSelect('d')
                  ->where("d.id = :dahira")
                  ->setParameter('dahira', $dahira);
                  // ->getQuery();

        return $qb;//->getResult();//
    }

    public function findLast(){
    	$qb = $this->createQueryBuilder('t')
    	           ->orderBy('t.id', 'DESC')
                     ->setMaxResults(1)
                     ->getQuery()
                     ->getResult();
                     // ->getSingleResult();
          if(empty($qb))
          	return 0;
          else
          	return $qb[0]->getId();
    }
}
