<?php

namespace Proxies\__CG__\Edahira\DahiraBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Dahira extends \Edahira\DahiraBundle\Entity\Dahira implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'nom', 'description', 'president', 'telephone', 'email', 'siege', 'numcompte', 'datecreation', 'caisses', 'categories', 'charges', 'evenement', 'membres', 'typeevenement', 'depenses', 'utilisateurs');
        }

        return array('__isInitialized__', 'id', 'nom', 'description', 'president', 'telephone', 'email', 'siege', 'numcompte', 'datecreation', 'caisses', 'categories', 'charges', 'evenement', 'membres', 'typeevenement', 'depenses', 'utilisateurs');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Dahira $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPresident($president)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPresident', array($president));

        return parent::setPresident($president);
    }

    /**
     * {@inheritDoc}
     */
    public function getPresident()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresident', array());

        return parent::getPresident();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', array($telephone));

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', array());

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiege($siege)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiege', array($siege));

        return parent::setSiege($siege);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiege()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiege', array());

        return parent::getSiege();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumcompte($numcompte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumcompte', array($numcompte));

        return parent::setNumcompte($numcompte);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumcompte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumcompte', array());

        return parent::getNumcompte();
    }

    /**
     * {@inheritDoc}
     */
    public function addCaiss(\Edahira\DahiraBundle\Entity\Caisses $caisses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCaiss', array($caisses));

        return parent::addCaiss($caisses);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCaiss(\Edahira\DahiraBundle\Entity\Caisses $caisses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCaiss', array($caisses));

        return parent::removeCaiss($caisses);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaisses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaisses', array());

        return parent::getCaisses();
    }

    /**
     * {@inheritDoc}
     */
    public function addCategory(\Edahira\DahiraBundle\Entity\Categories $categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategory', array($categories));

        return parent::addCategory($categories);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCategory(\Edahira\DahiraBundle\Entity\Categories $categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCategory', array($categories));

        return parent::removeCategory($categories);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategories', array());

        return parent::getCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function addCharge(\Edahira\DahiraBundle\Entity\Charges $charges)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCharge', array($charges));

        return parent::addCharge($charges);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCharge(\Edahira\DahiraBundle\Entity\Charges $charges)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCharge', array($charges));

        return parent::removeCharge($charges);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharges()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharges', array());

        return parent::getCharges();
    }

    /**
     * {@inheritDoc}
     */
    public function addEvenement(\Edahira\DahiraBundle\Entity\Evenement $evenement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEvenement', array($evenement));

        return parent::addEvenement($evenement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEvenement(\Edahira\DahiraBundle\Entity\Evenement $evenement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEvenement', array($evenement));

        return parent::removeEvenement($evenement);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvenement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvenement', array());

        return parent::getEvenement();
    }

    /**
     * {@inheritDoc}
     */
    public function addMembre(\Edahira\DahiraBundle\Entity\Membres $membres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMembre', array($membres));

        return parent::addMembre($membres);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMembre(\Edahira\DahiraBundle\Entity\Membres $membres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMembre', array($membres));

        return parent::removeMembre($membres);
    }

    /**
     * {@inheritDoc}
     */
    public function getMembres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMembres', array());

        return parent::getMembres();
    }

    /**
     * {@inheritDoc}
     */
    public function addTypeevenement(\Edahira\DahiraBundle\Entity\Typeevenement $typeevenement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTypeevenement', array($typeevenement));

        return parent::addTypeevenement($typeevenement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTypeevenement(\Edahira\DahiraBundle\Entity\Typeevenement $typeevenement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTypeevenement', array($typeevenement));

        return parent::removeTypeevenement($typeevenement);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeevenement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeevenement', array());

        return parent::getTypeevenement();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecreation($datecreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecreation', array($datecreation));

        return parent::setDatecreation($datecreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecreation', array());

        return parent::getDatecreation();
    }

    /**
     * {@inheritDoc}
     */
    public function addDepense(\Edahira\DahiraBundle\Entity\Depenses $depenses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDepense', array($depenses));

        return parent::addDepense($depenses);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDepense(\Edahira\DahiraBundle\Entity\Depenses $depenses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDepense', array($depenses));

        return parent::removeDepense($depenses);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepenses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepenses', array());

        return parent::getDepenses();
    }

    /**
     * {@inheritDoc}
     */
    public function addUtilisateur(\Edahira\UserBundle\Entity\Utilisateurs $utilisateurs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUtilisateur', array($utilisateurs));

        return parent::addUtilisateur($utilisateurs);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUtilisateur(\Edahira\UserBundle\Entity\Utilisateurs $utilisateurs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUtilisateur', array($utilisateurs));

        return parent::removeUtilisateur($utilisateurs);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilisateurs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilisateurs', array());

        return parent::getUtilisateurs();
    }

}
